# Generated by Django 3.0.6 on 2020-06-13 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_desired', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_name', models.CharField(default='Empty', max_length=100)),
                ('total', models.IntegerField(default=0)),
                ('date_start', models.DateField(auto_now=True)),
                ('date_end', models.DateField(auto_now=True)),
                ('deliver', models.BooleanField(default=True)),
                ('meals', models.ManyToManyField(blank=True, to='cart.CartItem')),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Profile')),
            ],
        ),
    ]
