# Generated by Django 3.0.7 on 2020-06-12 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='profile',
        ),
    ]
