# Generated by Django 3.0.6 on 2020-06-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('plan_id', models.IntegerField(default=1)),
                ('max_meals', models.IntegerField(default=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount', models.IntegerField(default=5)),
                ('image', models.ImageField(default='default.jpg', upload_to='images/plans')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('opening_year', models.CharField(max_length=4, null=True)),
                ('story', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_id', models.IntegerField(default=0)),
                ('dish', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='images/menu')),
                ('description', models.TextField(null=True)),
                ('restaurant', models.ManyToManyField(default=1, to='menu.Restaurant')),
            ],
        ),
    ]
